services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - RABBITMQ_URL=amqp://${RABBITMQ_USER}:${RABBITMQ_PASS}@rabbitmq:5672/
    depends_on:
      rabbitmq:
        condition: service_healthy

  transcription_worker:
    build:
      context: ./transcription_worker
    environment:
      - RABBITMQ_URL=amqp://${RABBITMQ_USER}:${RABBITMQ_PASS}@rabbitmq:5672/
      - BACKEND_URL=${BACKEND_URL}
      - INTERNAL_API_KEY=${INTERNAL_API_KEY}
    restart: unless-stopped
    depends_on:
      rabbitmq:
        condition: service_healthy

  embedding_worker:
    build:
      context: ./embedding_worker
    environment:
      - RABBITMQ_URL=amqp://${RABBITMQ_USER}:${RABBITMQ_PASS}@rabbitmq:5672/
      - DATABASE_URL=${DATABASE_URL}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - BACKEND_URL=${BACKEND_URL}
      - EMBEDDING_ENGINE=${EMBEDDING_ENGINE}
      - INTERNAL_API_KEY=${INTERNAL_API_KEY}
    restart: unless-stopped
    depends_on:
      rabbitmq:
        condition: service_healthy


  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASS}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  rabbitmq_data:
